Move and migrate install path

diff --git a/root/etc/cont-init.d/40-install b/root/etc/cont-init.d/40-install
--- a/root/etc/cont-init.d/40-install
+++ b/root/etc/cont-init.d/40-install
@@ -12,25 +12,37 @@ else
   exit 1
 fi
 
+if [[ -d /config/www/Dashboard ]]; then
+  echo '-----------------------'
+  echo '| Relocating Organizr |'
+  echo '-----------------------'
+  if [[ $(grep -c "root /config/www/Dashboard;" /config/nginx/site-confs/default) -eq 1 ]]; then
+    sed -i $'s|root /config/www/Dashboard;|root /config/www/organizr;|g' /config/nginx/site-confs/default
+  elif [[ $(grep -c "root /config/www/organizr;" /config/nginx/site-confs/default) -eq 0 ]]; then
+    echo "Root directive was not detected, unable to update nginx with the new location"
+  fi
+  mv /config/www/Dashboard /config/www/organizr
+fi
+
 # Fetch site or update existing
 if [ "$branch" == "manual" ]; then
   echo "Skipping update"
-elif [[ ! -d /config/www/Dashboard/.git ]]; then
+elif [[ ! -d /config/www/organizr/.git ]]; then
   echo '-----------------------'
   echo '| Installing Organizr |'
   echo '-----------------------'
-  mkdir -p /config/www/Dashboard
-  git clone --progress --verbose -b "$(cat /Docker.txt)" https://github.com/causefx/Organizr /config/www/Dashboard || exit 1
-  cd /config/www/Dashboard || (
+  mkdir -p /config/www/organizr
+  git clone --progress --verbose -b "$(cat /Docker.txt)" https://github.com/causefx/Organizr /config/www/organizr || exit 1
+  cd /config/www/organizr || (
     echo 'Failed to load Organizr repository folder'
     exit
   )
-  git rev-parse HEAD >/config/www/Dashboard/Github.txt
-elif [[ -d /config/www/Dashboard/.git ]]; then
+  git rev-parse HEAD >/config/www/organizr/Github.txt
+elif [[ -d /config/www/organizr/.git ]]; then
   echo '-----------------------'
   echo '|  Updating Organizr  |'
   echo '-----------------------'
-  cd /config/www/Dashboard || (
+  cd /config/www/organizr || (
     echo 'Failed to load Organizr repository folder'
     exit 0
   )
@@ -39,7 +51,7 @@ elif [[ -d /config/www/Dashboard/.git ]]; then
   git checkout "$(cat /Docker.txt)"
   git reset --hard origin/"$(cat /Docker.txt)"
   git pull
-  git rev-parse HEAD >/config/www/Dashboard/Github.txt
+  git rev-parse HEAD >/config/www/organizr/Github.txt
 elif ! ping -c 1 https://github.com &>/dev/null; then
   echo "Git clone failed, but github is resolvable"
 else
@@ -48,10 +60,10 @@ fi
 
 if [ ! "$branch" == "manual" ]; then
   # Make sure the config.php file is using the correct branch
-  sed -i "s/'branch' => '[^']*',/'branch' =\> '$branch',/" /config/www/Dashboard/api/config/config.php
+  sed -i "s/'branch' => '[^']*',/'branch' =\> '$branch',/" /config/www/organizr/api/config/config.php
 fi
 
-cp /Docker.txt /config/www/Dashboard/Docker.txt || (
+cp /Docker.txt /config/www/organizr/Docker.txt || (
   echo 'Failed to move Docker flag, are you running with the updater disabled?'
   exit 0
 )
